algoritmo "calcular_media"

// Função : Calcular a media de 2 notas e mostrar essa média
// Autor : Renato de Luna
// Data : 08/03/2018

// Seção de Declarações 
var
   nota1, nota2, media : Real

inicio
// Seção de Comandos
   escreva ("Digite a primeira nota : ")
   leia (nota1)
   escreva ("Digite a segunda nota : ")
   leia (nota2)
   media <- (nota1 + nota2) / 2
   escreval ("A media é : ", media)

fimalgoritmo