algoritmo "consorcio"
// Função : Duas variáveis (A e B) possuem valores distintos (A=5 e B=10), 
// Crie um algoritmo que armazene esse dois valores nessas duas variáveis,
// e efetue a troca dos valores de forma que a variável A passe a possuir o
// valor da variável B passe a possuir o valor da variável A. Por fim, 
// apresentar os valores trocado.
// Autor : Renato de Luna
// Data : 25/03/2018