algoritmo "prestacao"
// Função : Analisando a formula "prestação = valor + valor * (taxa / 100)", crie
// um algoritmo para efetuar o cáculo do valor de uma prestação em atraso. ( Voce
// deverá ler o valor da prestação, a Taxa de juros imposta pelo banco, e o número
// dias em abraso.
// Autor : Renato de Luna
// Data : 23/03/2018

// Seção de Declarações 
var

inicio
// Seção de Comandos 

fimalgoritmo